**Most relevant conclussions from the first correlations analysis**
1. The sellers with a more recent creation date have not experienced an improved average delivery days for the previous orders, compared vs older sellers
2. The sellers focus on working with different clients, the repurchase level has to be low because there is a positive correlation between the number of orders and number of clients. Only 1 appeas to have a solid base of existing clients
3. There isn't a clear correlation betwen the total earnings and the total categories where they have sold their products, meaning that they do not tend to specialize on a specific category. This is also seen in the correlation between shared products and total categories 
4. The sellers with a more recent creation date are on average, don't have on average more earnings per order compared to older seller, nor their client price is bigger

In [7]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as scipy
from scipy import stats
from scipy.stats import chi2_contingency
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [5]:
dfsellers8 = pd.read_csv("../data/elenas-it1-preprocessed3.csv", index_col=0)

[ ] Document and rename the data wrangling notebook
[ ] Run the correlation and hypothesis tests on this notebook
[ ] Create a file with the functions

Mirar las magnitudes de ambas positivas y negativas

*null hypothesis* $H_0$, and $H_1$

<center> $H_0$: Medicine does nothing. $\;\; vs \;\;$  $H_1$: Medicine does something. </center>

With hypothesis testing, we assume that the Null Hypothesis is true and then gather data to see whether there is enough evidence to disprove this assumption. In our example, we might give one group of patients the medicine and give another group of patients a placebo, then measure the average change in blood pressure of each group. It is only when the difference between the placebo group and the drug group is significantly big enough that we would conclude that the drug has an effect. (We will soon explore how to define what "big enough" means.)

In [6]:
dfsellers8.head(5)
dfsellers8.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'seller_id', 'created_at', 'user_id',
       'total_orders', 'effective_ratio', 'rto_ratio', 'return_ratio',
       'cancelled_ratio', 'departments_sold', 'number_of_clients',
       'avg_effective_delivery_days', 'total_effective_earnings',
       'avg_effective_earnings', 'avg_client_price', 'avg_shipment_cost',
       'total_discount', 'avg_discount', 'order_last_month', 'is_referred',
       'has_referred', 'avg_cart_items', 'avg_vendor_discount',
       'number_of_products', 'number_of_photos', 'number_of_categories',
       'average_prod_existence_days', 'total_products_shared',
       'number_of_credits', 'number_of_used_credits', 'avg_credit_amount',
       'number_of_vouchers'],
      dtype='object')

In [8]:
dfsellers8["order_last_month"].sum()

# for loop with this column as a constant

27407

In [30]:
dfsellers8.drop

,Unnamed: 0.1,seller_id,created_at,user_id,total_orders,effective_ratio,rto_ratio,return_ratio,cancelled_ratio,departments_sold,...,avg_vendor_discount,number_of_products,number_of_photos,number_of_categories,average_prod_existence_days,total_products_shared,number_of_credits,number_of_used_credits,avg_credit_amount,number_of_vouchers
0,0,11571677,2022-12-08,11600263,3.0,1.00,0.00,0.00,0.00,1.0,...,0.00,3,0,3,453.00,1,27,0,6222.22,39
1,1,11583955,2022-12-11,11612556,1.0,1.00,0.00,0.00,0.00,1.0,...,7485.00,1,0,1,423.00,0,12,0,6500.00,25
2,2,11604304,2022-12-16,11632958,7.0,0.71,0.00,0.14,0.14,1.0,...,186.88,6,0,4,410.50,5,24,0,6875.00,46
3,3,11621203,2022-12-23,11649875,3.0,0.33,0.33,0.00,0.33,1.0,...,7581.67,3,0,2,621.33,0,7,0,4428.57,26
4,4,11634194,2022-12-31,11662886,1.0,0.00,0.00,0.00,1.00,1.0,...,3800.00,1,0,1,423.00,0,3,0,7333.33,7

In [32]:
pd.read_csv("elenas-it1-preprocessed3.csv", index_col=0)

,Unnamed: 0.1,seller_id,created_at,user_id,total_orders,effective_ratio,rto_ratio,return_ratio,cancelled_ratio,departments_sold,...,avg_vendor_discount,number_of_products,number_of_photos,number_of_categories,average_prod_existence_days,total_products_shared,number_of_credits,number_of_used_credits,avg_credit_amount,number_of_vouchers
0,0,11571677,2022-12-08,11600263,3.0,1.000000,0.000000,0.000000,0.000000,1.0,...,0.000000,3,0,3,453.000000,1,27,0,6222.222222,39
1,1,11583955,2022-12-11,11612556,1.0,1.000000,0.000000,0.000000,0.000000,1.0,...,7485.000000,1,0,1,423.000000,0,12,0,6500.000000,25
2,2,11604304,2022-12-16,11632958,7.0,0.714286,0.000000,0.142857,0.142857,1.0,...,186.875000,6,0,4,410.500000,5,24,0,6875.000000,46
3,3,11621203,2022-12-23,11649875,3.0,0.333333,0.333333,0.000000,0.333333,1.0,...,7581.666667,3,0,2,621.333333,0,7,0,4428.571429,26
4,4,11634194,2022-12-31,11662886,1.0,0.000000,0.000000,0.000000,1.000000,1.0,...,3800.000000,1,0,1,423.000000,0,3,0,7333.333333,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263260,263260,11391291,2022-09-22,11419567,1.0,0.000000,0.000000,1.000000,0.000000,1.0,...,0.000000,1,0,1,283.000000,2,15,0,6466.666667,44
263261,263261,11391299,2022-09-22,11419575,5.0,0.800000,0.000000,0.000000,0.200000,1.0,...,0.000000,4,0,4,301.600000,2,22,0,7090.909091,52
263262,263262,11391304,2022-09-22,11419580,3.0,0.000000,1.000000,0.000000,0.000000,1.0,...,7590.000000,2,0,2,562.333333,3,2,0,6500.000000,17
263263,263263,11389365,2022-09-22,11417638,8.0,0.375000,0.250000,0.000000,0.375000,3.0,...,136480.500000,6,0,3,530.625000,17,39,0,7076.923077,84
263264,263264,10761435,2022-01-25,10773070,5.0,0.800000,0.200000,0.000000,0.000000,1.0,...,1893.833333,4,0,4,399.833333,5,30,0,7166.666667,72

In [ ]:
def num_vis(df, row, col, colorp):
    # Initialization with the rows and columns for the subplot
    fig = make_subplots(rows=row, cols=col)
    
    # List of the numerical columns
    numeric_columns = df.select_dtypes(exclude=["object"]).columns.to_list()
    
    # Loop, iterating on each column
    for i, column in enumerate(numeric_columns):
        # Number of rows based on index
        row_num = (i // col) + 1
        # Number of columns based on index, + 1 to start on the first position and have an integer
        col_num = (i % col) + 1
        
        # Histogram of the variables
        hist = px.histogram(df, x=column, color_discrete_sequence=px.colors.qualitative.Plotly)
        
        fig.add_trace(hist.data[0], row=row_num, col=col_num)
        fig.update_xaxes(title_text=column, row=row_num, col=col_num)
        fig.update_yaxes(title_text="Count", row=row_num, col=col_num)
    
    fig.update_layout(height=400*row, width=400*col)
    fig.show()

num_vis(dfsellers7.round(1), 6, 6, "RdPu")

In [ ]:
dfsellers7.describe().transpose()

In [ ]:
#Operational metrics
def boxplot_vis(df, col1=0, col2=0, col3=0, col4=0, col5=0, col6=0):
    # Create subplot with 2 rows and 3 columns
    fig = make_subplots(rows=2, cols=3)

    # Visualization for each value
    if col1 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col1).data[0], row=1, col=1)
        fig.update_xaxes(title_text=col1, row=1, col=1)
        fig.update_yaxes(title_text=input("write the y axis for the plot 1: "), row=1, col=1)
    if col2 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col2).data[0], row=1, col=2)
        fig.update_xaxes(title_text=col2, row=1, col=2)
        fig.update_yaxes(title_text=input("write the y axis for the plot 2: "), row=1, col=2)
    if col3 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col3).data[0], row=1, col=3)
        fig.update_xaxes(title_text=col3, row=1, col=3)
        fig.update_yaxes(title_text=input("write the y axis for the plot 3: "), row=1, col=3)
    if col4 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col4).data[0], row=2, col=1)
        fig.update_xaxes(title_text=col4, row=2, col=1)
        fig.update_yaxes(title_text=input("write the y axis for the plot 4: "), row=2, col=1)
    if col5 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col5).data[0], row=2, col=2)
        fig.update_xaxes(title_text=col5, row=2, col=2)
        fig.update_yaxes(title_text=input("write the y axis for the plot 5: "), row=2, col=2)
    if col6 != 0:
        fig.add_trace(px.box(data_frame=df.round(0), y=col6).data[0], row=2, col=3)
        fig.update_xaxes(title_text=col6, row=2, col=3)
        fig.update_yaxes(title_text=input("write the y axis for the plot 6: "), row=2, col=3)

    # Show the figure
    fig.show()

### Transactional information:

**Earnings**

- On average, the sellers have earned COP 175.000 using Elenas, although this number is not an adequate measure since it combines sellers that have been working for different time periods, and with different usage levels. The maximum a that a seller within this sample has earned is COP 158M which is approximately USD 400K

- There is a neutral correlation between the seller creation date and the average earnings. Meaning that over time, the sellers are not earning more on average. There is an increase in the last months but it is marginal. This can also be confirmed by the correlation of seller creation date and average end client price

- All the sellers are using the assigned credits, this is not a pattern of the older or newer sellers, which can be affirmed since there is no correlation between the metrics

In [ ]:


#Boxplots: earnings

# Create subplot with 1 row and 2 columns
fig = make_subplots(rows=1, cols=2)

# Add box plots to the subplots
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='total_effective_earnings').data[0], row=1, col=1)
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='avg_effective_earnings').data[0], row=1, col=2)

# Update layout
fig.update_layout(title='Total earning and average earning distribution')
fig.update_xaxes(title_text='Total earnings', row=1, col=1)
fig.update_xaxes(title_text='Average earnings', row=1, col=2)
fig.update_yaxes(title_text='COP', row=1, col=1)
fig.update_yaxes(title_text='COP', row=1, col=2)


# Show the figure
fig.show()

In [ ]:
#Boxplots: credits & vouchers

# Boxplots: credits & vouchers

# Create subplot with 1 row and 2 columns
fig = make_subplots(rows=2, cols=2)

# Add box plots to the subplots
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='number_of_credits').data[0], row=1, col=1)
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='avg_credit_amount').data[0], row=1, col=2)


# Update layout
fig.update_layout(title='Usage of credits')
fig.update_xaxes(title_text='# of credits', row=1, col=1)
fig.update_xaxes(title_text='Average credit amount', row=1, col=2)
fig.update_yaxes(title_text='Counts', row=1, col=1)
fig.update_yaxes(title_text='Counts', row=1, col=2)

# Show the figure
fig.show()

In [ ]:
#Boxplots: credits & vouchers

# Boxplots: vouchers

# Create subplot with 1 row and 2 columns
fig = make_subplots(rows=2, cols=2)

# Add box plots to the subplots
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='number_of_used_credits').data[0], row=1, col=1)
fig.add_trace(px.box(data_frame=dfsellers7.round(0), y='number_of_vouchers').data[0], row=1, col=2)


# Update layout
fig.update_layout(title='Usage of credits')
fig.update_xaxes(title_text='number_of_used_credits', row=1, col=1)
fig.update_xaxes(title_text='number_of_vouchers', row=1, col=2)
fig.update_yaxes(title_text='Counts', row=1, col=1)
fig.update_yaxes(title_text='Counts', row=1, col=2)

# Show the figure
fig.show()

In [ ]:
fig = px.scatter(dfsellers7, x='created_at', y='avg_effective_earnings', title='Seller creation date vs Avg earnings',
                 labels={'created_at': 'Seller creation date', 'avg_effective_earnings': 'Avg earnings'})

fig.update_layout(xaxis_title='Seller creation date', yaxis_title='Avg effective earnings')
fig.show()

In [ ]:
fig = px.scatter(dfsellers7, x='created_at', y='avg_client_price', title='Seller creation date vs Avg client price',
                 labels={'created_at': 'Seller creation date', 'avg_client_price': 'Avg client price'})

fig.update_layout(xaxis_title='Seller creation date', yaxis_title='Avg client price')
fig.show()

In [ ]:
fig = px.scatter(dfsellers7, x='created_at', y='number_of_used_credits', title='Seller creation date vs Number of used credits',
                 labels={'created_at': 'Seller creation date', 'number_of_used_credits': 'Total used credits'})

fig.update_layout(xaxis_title='Seller creation date', yaxis_title='Total used credits')
fig.show()

Operational data:
ratios

The ratios behave as in a positive but expected pattern, the effective ratio is skewed to the right, meaning that a majority of orders are effective, while the negative ones are skewed to the left, meaning that most orders do not have a negative outcome.

The average delivery days for effecive orders is 5.4 days, which is quite similar to the median.

The sellers with a most recent seller creation date do not experience on average a decrease in the average delivery days

In [ ]:
# Create subplot with 1 row and 2 columns
fig = make_subplots(rows=2, cols=2)

# Add box plots to the subplots
fig.add_trace(px.box(data_frame=dfsellers7.round(3), y='effective_ratio').data[0], row=1, col=1)
fig.add_trace(px.box(data_frame=dfsellers7.round(3), y='rto_ratio').data[0], row=1, col=2)
fig.add_trace(px.box(data_frame=dfsellers7.round(3), y='return_ratio').data[0], row=2, col=1)
fig.add_trace(px.box(data_frame=dfsellers7.round(3), y='cancelled_ratio').data[0], row=2, col=2)


# Update layout
fig.update_layout(title='Operational ratios')
fig.update_xaxes(title_text='effective_ratio', row=1, col=1)
fig.update_xaxes(title_text='rto_ratio', row=1, col=2)
fig.update_xaxes(title_text='return_ratio', row=1, col=1)
fig.update_xaxes(title_text='cancelled_ratio', row=1, col=2)
fig.update_yaxes(title_text='Counts', row=1, col=1)
fig.update_yaxes(title_text='Counts', row=1, col=2)
fig.update_yaxes(title_text='Counts', row=2, col=1)
fig.update_yaxes(title_text='Counts', row=2, col=2)

fig.show()

In [ ]:
# Create subplot with 1 row and 2 columns
fig = make_subplots(rows=2, cols=2)

# Add histograms to the subplots
fig.add_trace(px.histogram(data_frame=dfsellers7.round(3), x='effective_ratio', nbins=20).data[0], row=1, col=1)
fig.add_trace(px.histogram(data_frame=dfsellers7.round(3), x='rto_ratio', nbins=20).data[0], row=1, col=2)
fig.add_trace(px.histogram(data_frame=dfsellers7.round(3), x='return_ratio', nbins=20).data[0], row=2, col=1)
fig.add_trace(px.histogram(data_frame=dfsellers7.round(3), x='cancelled_ratio', nbins=20).data[0], row=2, col=2)

# Update layout
fig.update_layout(title='Operational ratios')
fig.update_xaxes(title_text='Effective Ratio', row=1, col=1)
fig.update_xaxes(title_text='RTO Ratio', row=1, col=2)
fig.update_xaxes(title_text='Return Ratio', row=2, col=1)
fig.update_xaxes(title_text='Cancelled Ratio', row=2, col=2)
fig.update_yaxes(title_text='Counts', row=1, col=1)
fig.update_yaxes(title_text='Counts', row=1, col=2)
fig.update_yaxes(title_text='Counts', row=2, col=1)
fig.update_yaxes(title_text='Counts', row=2, col=2)

fig.show()

In [ ]:
# departments:

departments = dfsellers7["departments_sold"].round(0).value_counts().sort_values(ascending=False).iloc[:10]
departments = departments.reset_index()  # Reset the index to make 'index' as a column

fig = px.bar(departments,
              x='index',
              y='departments_sold',
              title="Number of departments where the sellers have sold")
fig.update_layout(xaxis_title="Number of departments", yaxis_title="Number of orders")
fig.show()

In [ ]:
departments = dfsellers7["departments_sold"].round(0).value_counts().sort_values(ascending=False).iloc[:10]
departments

In [ ]:
#Relationship between delivery days and sellers creation date
fig = px.scatter(dfsellers7, x='created_at', y='avg_effective_delivery_days', title='Seller creation date vs Avg effective orders delivery days',
                 labels={'created_at': 'Seller creation date', 'avg_effective_delivery_days': 'Average effective orders delivery days'})

fig.update_layout(xaxis_title='Seller creation date', yaxis_title='avg delivery days')
fig.show()

## Behavioral columns

- The sellers focus on working with different clients, the repurchase level has to be low because there is a positive correlation between the number of orders and number of clients. Only 1 appeas to have a solid base of existing clients

- There isn't a clear correlation betwen the total earnings and the total categories where they have sold their products, meaning that they do not tend to specialize on a specific category. This is also seen in the correlation between shared products and total categories

In [ ]:
#Relationship between orders and clients

fig = px.scatter(dfsellers7, x='number_of_clients', y='total_orders', title='Total Orders vs Total Clients',
                 labels={'total_clients': 'Total Clients', 'total_orders': 'Total Orders'})

fig.update_layout(xaxis_title='Total Clients', yaxis_title='Total Orders')
fig.show()

In [ ]:
#Relationship between earnings and clients

fig = px.scatter(dfsellers7, x='number_of_clients', y='total_effective_earnings', title='Total earnings vs Total Clients',
                 labels={'total_clients': 'Total Clients', 'total_effective_earnings': 'Total effective earnings'})

fig.update_layout(xaxis_title='Total Clients', yaxis_title='Total effective earnings')
fig.show()

In [ ]:
#Relationship between earnings and categories

fig = px.scatter(dfsellers7, x='number_of_categories', y='total_effective_earnings', title='Total categories vs Total earnings',
                 labels={'number_of_categories': 'Total Categories', 'total_effective_earnings': 'Total effective earnings'})

fig.update_layout(xaxis_title='Number of categories', yaxis_title='Total effective earnings')
fig.show()

In [ ]:
#Relationship between product shared and categories

fig = px.scatter(dfsellers7, x='number_of_categories', y='total_products_shared', title='Total categories vs Total number of shared products',
                 labels={'number_of_categories': 'Total Categories', 'total_products_shared': 'Total number of shared products'})

fig.update_layout(xaxis_title='Number of categories', yaxis_title='Total number of shared products')
fig.show()

## Correlations

In [ ]:
sns.set_theme(style="white")

# Compute the correlation matrix
corr = dfsellers7.corr().round(2)

# Generate a mask for the upper triangle
mask = np.triu(np.ones_like(corr, dtype=bool))

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(30, 20))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(230, 20, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, vmin=-1, vmax=1, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5}, annot=True)
plt.title("Correlation matrix")